---
version: "2"
plugins:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - java
        - javascript
        - python
        - c
  eslint:
    enabled: true
  fixme:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 70
  return-statements:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 40
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - scripts/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
